server:
  port: 8080

spring:
  application:
    name:INTERACATION_SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/metube
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Soh1b0407}
  jpa:
    hibernate:
      ddl-auto:update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgresSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${DB_HOST:localhost}:8761/eurika/}
  instance:
    preferIpAdress: true
